version: '3.5'

services:
  app:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: lab-rails
    volumes:
      - .:/lab-rails
    ports:
      - "3005:3005"
    expose:
      - "3005"
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:10.5
    container_name: lab-rails-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
    ports: ["5432:5432"]
    expose: ["5432"]
