default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: secretpassword
  database: lab-rails_development

test:
  <<: *default
  username: root
  password: secretpassword
  database: lab-rails_test

production:
  <<: *default
  database: lab-rails # Create an Env for database name.
  username: lab-rails
  password: secretpassword