WIRECARD_SANDBOX_TOKEN: "HI4K9J9ESGKNAT0PF7HOQLGJZESXPXHV"
WIRECARD_SANDBOX_KEY: "X1RPGXAXJ4G57D0DQGFOR9Y1FEMUAAZISVN9DDKI"
WIRECARD_SANDBOX_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0/3z+VVPrzW4m3U4ZH+j
AK7jPTlIJtR7QeZ2iqv/lpP0rDFIt4Veu4+jksgfShrpmq9zQJylbcI7qWQ/QqFS
nVCHtuEQIDZOv5433LYpSxbiH7nJQkHTk5DKNkw7btO+8l005TPCDyo815waGi1A
c9BwLiZomuzKT1CegnPRED+O/y3ooXBUVlcj/WqKgCFr8jKi8NOrj84Nwr262i3T
nVL3Ypx79XuSDmicSXLlhaiCWNSipdF29iKx0hcKmiJiR3T9QThJZ1heTJ1H21V4
S/fpuRfgG/1MVCmoD0pBm1SKaLMYYD/MnEsIo7DB6PkD0Lx4aaRMCq92Bt8t/Jep
MwIDAQAB
-----END PUBLIC KEY-----
"

LOCAL_ROOT_URL: "https://0c215514.ngrok.io"